### ISSUE TITLE
Give item command seems broken 

### ISSUE THREAD

**Issue by MaceUD** [TheCrunchy/FixPlayerCommand#12]
Hey ! 

I believe the give item command might be broken. The log I got all the time is this : 

`21:57:49.2165 [ERROR]  Torch.Commands.Command: Command '!giveitem <String PlayerName> <String type> <String subtypeName> <Int64 amount> [Boolean force] ' from 'CrunchUtils' threw an exception. Args: Strotter, Component, SuperComputer, 10000, true
21:57:49.2165 [ERROR]  Torch.Commands.Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CrunchUtilities.Commands.PlayerWithdraw(String PlayerName, String type, String subtypeName, Int64 amount, Boolean force) in C:\Users\Cameron\Documents\3 Torch Plugins\FixPlayerCommand\FixPlayerCommand\Commands.cs:line 1063
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CrunchUtilities.Commands.PlayerWithdraw(String PlayerName, String type, String subtypeName, Int64 amount, Boolean force) in C:\Users\Cameron\Documents\3 Torch Plugins\FixPlayerCommand\FixPlayerCommand\Commands.cs:line 1063
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
21:57:49.2165 [INFO]   Torch.Commands.CommandManager: Server ran command '!giveitem "Strotter" Component SuperComputer 10000 true'`

Thanks for your time !
Mace

**Comment by TheCrunchy** [comment]
Try the latest version

**Comment by MaceUD** [comment]
Fixed
