### ISSUE TITLE
!giveitem will sometimes fail

### ISSUE THREAD

**Issue by Acharnite** [TheCrunchy/FixPlayerCommand#16]
Hello there.
For the past couple of weeks, CrunchUtils have failed to process !giveitem.
Recently today it failed to run the command at 18:30, but then ran the command succesfully at 20:30

This is the error from the failed attempt:
`18:29:41.3847 [ERROR]  Torch.Commands.Command: Command '!giveitem <String PlayerName> <String type> <String subtypeName> <Int32 amount> [Boolean force] ' from 'CrunchUtils' threw an exception. Args: Ketmo, Component, SuperComputer, 10000, true
18:29:41.3847 [ERROR]  Torch.Commands.Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CrunchUtilities.Commands.PlayerWithdraw(String PlayerName, String type, String subtypeName, Int32 amount, Boolean force) in C:\Users\Cameron\Documents\3 Torch Plugins\FixPlayerCommand\FixPlayerCommand\Commands.cs:line 3199
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\build\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CrunchUtilities.Commands.PlayerWithdraw(String PlayerName, String type, String subtypeName, Int32 amount, Boolean force) in C:\Users\Cameron\Documents\3 Torch Plugins\FixPlayerCommand\FixPlayerCommand\Commands.cs:line 3199
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\build\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
18:29:41.3847 [INFO]   Torch.Commands.CommandManager: Server ran command '!giveitem "Ketmo" Component SuperComputer 10000 true'`

I ran the command manually afterwards, and it worked again flawlessly.

**Comment by TheCrunchy** [comment]
That error is from trying to give an item to a player that has no character alive

**Comment by Acharnite** [comment]
Would it be possible for it to give an error saying something in those lines, instead of it just spitting out an error code like that :)

It would help trying to figure out what went wrong, as these errors above are very hard to debug, when you don't know the inner workings of some code.

**Comment by TheCrunchy** [comment]
Fixed
