### ISSUE TITLE
listnames from torch console is broken.

### ISSUE THREAD

**Issue by dorimanx** [TheCrunchy/FixPlayerCommand#3]
```
13:18:40.9131 [ERROR]  Command: Command '!listnames ' from 'CrunchUtils' threw an exception. Args: 
13:18:40.9131 [ERROR]  Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CrunchUtilities.Commands.listNames() in C:\Users\Cameron\Documents\3 Torch Plugins\FixPlayerCommand\FixPlayerCommand\Commands.cs:line 384
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CrunchUtilities.Commands.listNames() in C:\Users\Cameron\Documents\3 Torch Plugins\FixPlayerCommand\FixPlayerCommand\Commands.cs:line 384
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
13:18:40.9131 [INFO]   CommandManager: Server ran command '!listnames'
```

**Comment by TheCrunchy** [comment]
Fixed
