### ISSUE TITLE
giveitem from torch console return exception. but item is delivered!

### ISSUE THREAD

**Issue by dorimanx** [TheCrunchy/FixPlayerCommand#9]
Hi,
I have sent item to player backpack with force (true) he got the item, but i see exeption in console.

`
12:08:37.0790 [ERROR]  Command: Command '!giveitem <String PlayerName> <String type> <String subtypeName> <Int64 amount> [Boolean force] ' from 'CrunchUtils' threw an exception. Args: lhotski, component, PrometeusIngot, 8, true
12:08:37.0790 [ERROR]  Command: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CrunchUtilities.Commands.PlayerWithdraw(String PlayerName, String type, String subtypeName, Int64 amount, Boolean force) in C:\Users\Cameron\Documents\3 Torch Plugins\FixPlayerCommand\FixPlayerCommand\Commands.cs:line 1025
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CrunchUtilities.Commands.PlayerWithdraw(String PlayerName, String type, String subtypeName, Int64 amount, Boolean force) in C:\Users\Cameron\Documents\3 Torch Plugins\FixPlayerCommand\FixPlayerCommand\Commands.cs:line 1025
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Commands.Command.TryInvoke(CommandContext context) in C:\jenkins\workspace\Torch_Torch_master\Torch\Commands\Command.cs:line 145
12:08:37.0830 [INFO]   CommandManager: Server ran command '!giveitem lhotski component PrometeusIngot 8 true'
`

**Comment by TheCrunchy** [comment]
Fixed
